name: Node CI

# on:
#   schedule:
#   - cron: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59 * * * *

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        ./set_github_ssh_key.sh
        git config user.name "ykhirao-bot"
        git config user.email "yuki.dees39th@gmail.com"
        # git remote rm origin
        git remote set-url origin https://ykhirao:${{ secrets.GITHUB_PASS }}@github.com/ykhirao/write-code-everyday-bot
        # git remote set-url origin git@github.com:ykhirao/write-code-everyday-bot.git
        git fetch
        git branch
        git checkout master
        npm run add:text
        git add .
        git commit -m "update!"
        git push origin master
      env:
        CI: true
        SSH_KEY: ${{ secrets.SSH_KEY }}
